# Generated by Django 5.0.10 on 2025-03-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
